### ISSUE TITLE
Should this work on an Electron?  Can it be made to?

### ISSUE THREAD

**Issue by mincebert** [tom-seddon/basic_editor#17]
Hello — not sure if this is actually a valid issue, but should this work on an Electron?

If I load in the regular (non-Hi) version 1.44, it sort-of works: I can mostly edit a file, but it hangs if I try scrolling the screen.  Oddly the cursor doesn't flash, either.

I haven't done any investigation but I was wondering whether you knew it would be a major piece of work to get it running, or it should work and there are just some potential minor issues that need resolving (not that I'm expecting you to do it, particularly!).

I've also tried the Acornsoft 1.32 and 1.35 versions: 1.32 just hangs when I try to start it; 1.35 seems to show no cursor and hangs when I scroll, in the same way, so I don't think your updates have broken anything!

Thanks!

**Comment by tom-seddon** [comment]
`write_crtc` uses OSBYTE 151 to write to the 6845 directly at $fe00/$fe01: https://github.com/tom-seddon/basic_editor/blob/038e0807662e114258c6c6c524af0ddece5387fa/mainpart.s65#L4816 - that's probably going to cause problems!

Looks like it only uses it to change the cursor shape. Presumably you can do something similar on the Electron? The Beeb has VDU 23,1 for visibility/flash so I assume the Electron lets you do at least that.

--Tom

**Comment by mincebert** [comment]
Thanks for that — I don't think the ULA on the Electron lets you control the cursor height: you can only hide/show or make the cursor steady/flashing, so I think the simplest alternative here is to change it to steady for overwrite and flashing for insert using VDU 23.

I'll start with that and see where it gets me, thanks — I can't see any other calls to write_crtc other than to set the cursor for insert/overwrite, so that should resolve that.  I can't see where it would upset the scrolling, though, but that's step 2.

 I'm likely to be back but you're starting me in the write direction!

**Comment by mincebert** [comment]
Well, replacing all that seems to have solved the two obvious problems: the cursor is now steady for overwrite and flashing for insert and make_cursor_invisble also uses VDU 23 and it's no longer crashing when it scrolls.  I'm not aware of anything else that's a problem at the moment..

I'll give it a bit more of an exercise tomorrow and see if it all seems OK.  If so, I'll tidy it up and send a pull request.

**Comment by mincebert** [comment]
All done and I've sent a pull request.

The remainder of the work was sorting out the keyboard, which works very differently on the Electron: I got more involved in OSBYTE 226 and 227 than I ever wanted to!

Thanks for your help!
