### ISSUE TITLE
Basic Extensions / HiBasic... eg. While - Endwhile

### ISSUE THREAD

**Issue by Andrewcee** [tom-seddon/basic_editor#20]
Hi Folks,

Thanks for an excellent tool!

With PiTube co-pros readily and cheaply available for the beeb, have started experimenting with HiBasic and Advanced Basic so as to take advantage of the likes of While/Endwhile. Does the Basic Editor recognise the 'new' keywords? Using 1.45 it looks to change While to 'LOADACS' and Endwhile to 'EDIT'?

Thanks,
Andrew

**Comment by tom-seddon** [comment]
I'll update the docs with a note about this! I'm afraid the BASIC Editor only supports the following Acorn 6502 BASICs:

* BASIC II
* BASIC III (original 6502 HIBASIC)
* BASIC IV (BASIC on Master 128/Master Compact)

New keywords provided by 3rd party BASICs aren't supported, nor are any of the new tokens in BASIC V (BASIC on the Archimedes). There's not all that much room left in the ROM at this point, so It's rather unlikely this will change.
